name: ml-workshop
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - seaborn
  - ipykernel
  - ipywidgets
  - ipyleaflet
  - matplotlib
  - pandas
  - pyproj
  - xlrd
  - sympy
  - scikit-learn
  - jupyter